# Generated by Django 2.1.4 on 2019-01-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0003_autogeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='autogeneration',
            name='year_gen',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
