# Generated by Django 2.1.4 on 2019-01-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_autogeneration_year_gen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autogeneration',
            old_name='year_gen',
            new_name='year',
        ),
    ]
