# Generated by Django 2.1.5 on 2019-01-14 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0005_auto_20190110_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGarazhe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dver_firstright_title', models.CharField(max_length=50)),
                ('dver_firstright_on_hand', models.BooleanField()),
                ('dver_firstright_price', models.IntegerField()),
                ('dver_firstleft_title', models.CharField(max_length=50)),
                ('dver_firstleft_on_hand', models.BooleanField()),
                ('dver_firstleft_price', models.IntegerField()),
                ('dver_backright_title', models.CharField(max_length=50)),
                ('dver_backright_on_hand', models.BooleanField()),
                ('dver_backright_price', models.IntegerField()),
                ('dver_backleft_title', models.CharField(max_length=50)),
                ('dver_backleft_on_hand', models.BooleanField()),
                ('dver_backleft_price', models.IntegerField()),
                ('dver_kapot_title', models.CharField(max_length=50)),
                ('dver_kapot_on_hand', models.BooleanField()),
                ('dver_kapot_price', models.IntegerField()),
                ('dver_bagazhnik_title', models.CharField(max_length=50)),
                ('dver_bagazhnik_on_hand', models.BooleanField()),
                ('dver_bagazhnik_price', models.IntegerField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoGeneration')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoMark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoModel')),
            ],
        ),
    ]
