# Generated by Django 2.1.5 on 2019-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0006_testgarazhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetailTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('value', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='testgarazhe',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='testgarazhe',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='testgarazhe',
            name='model',
        ),
        migrations.DeleteModel(
            name='TestGarazhe',
        ),
    ]
