# Generated by Django 2.1.5 on 2019-01-16 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0008_autocolor_autoenginesize_autoenginetype_autokuzov_autotransmission_autoyearproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probeg', models.IntegerField()),
                ('vin_number', models.CharField(max_length=50)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoColor')),
                ('engine_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoEngineSize')),
                ('engine_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoEngineType')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoGeneration')),
                ('kuzov', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoKuzov')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoMark')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoModel')),
                ('ransmission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoTransmission')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lk.AutoYearProduction')),
            ],
        ),
    ]
