# Generated by Django 2.1.5 on 2019-01-16 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0010_stockroomtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockroomtest',
            name='donor_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lk.AutoDonor'),
        ),
    ]
