# Generated by Django 2.1.5 on 2019-01-30 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0017_stockroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockroomtest',
            name='stockroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lk.StockRoom'),
            preserve_default=False,
        ),
    ]
