# Generated by Django 2.1.5 on 2019-01-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0018_stockroomtest_stockroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockroomtest',
            name='stockroom',
        ),
    ]
