# Generated by Django 2.1.5 on 2019-01-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0019_remove_stockroomtest_stockroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockroomtest',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='stockroomtest',
            name='donor_info',
        ),
        migrations.DeleteModel(
            name='StockRoomTest',
        ),
    ]
