# Generated by Django 2.1.5 on 2019-01-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0020_auto_20190130_0924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockRoom',
        ),
    ]
