# Generated by Django 2.1.5 on 2019-01-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0030_delete_stockroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='userdetal',
            name='stockroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lk.Stock'),
            preserve_default=False,
        ),
    ]
