# Generated by Django 2.1.5 on 2019-01-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0033_userdetal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='photo',
            field=models.ImageField(upload_to='static/detals'),
        ),
    ]
