# Generated by Django 2.1.5 on 2019-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0036_auto_20190130_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
