# Generated by Django 2.1.5 on 2019-01-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0037_auto_20190131_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='photo',
            field=models.ImageField(blank=True, default='detals/nophoto.png', null=True, upload_to=''),
        ),
    ]
