# Generated by Django 2.1.5 on 2019-01-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0038_auto_20190131_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='photo',
            field=models.ImageField(blank=True, default='/nophoto.png', null=True, upload_to=''),
        ),
    ]
