# Generated by Django 2.1.5 on 2019-01-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0040_auto_20190131_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
