# Generated by Django 2.1.5 on 2019-01-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0041_auto_20190131_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
