# Generated by Django 2.1.5 on 2019-02-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0048_auto_20190205_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDetalMainGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
            ],
        ),
    ]
