# Generated by Django 2.1.5 on 2019-02-14 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0051_auto_20190213_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
