# Generated by Django 2.1.5 on 2019-02-26 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0055_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='staff_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
