# Generated by Django 2.1.5 on 2019-02-26 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0056_company_staff_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='staff_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
