# Generated by Django 2.1.5 on 2019-02-26 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0057_auto_20190226_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='staff_users',
            field=models.ManyToManyField(blank=True, choices=[('1', 'Freshman'), ('2', 'Sophomore'), ('3', 'Junior'), ('4', 'Senior')], to=settings.AUTH_USER_MODEL),
        ),
    ]
