# Generated by Django 2.1.5 on 2019-02-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0060_auto_20190227_1130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutoDetailTest',
            new_name='AutoDetal',
        ),
        migrations.RenameField(
            model_name='userdetal',
            old_name='detail',
            new_name='detal',
        ),
    ]
