# Generated by Django 2.1.5 on 2019-02-28 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0062_auto_20190228_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='value',
        ),
    ]
