# Generated by Django 2.1.5 on 2019-03-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0063_remove_stock_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'permissions': (('view_company_stock', 'Просмотр складов компании'), ('find_reactor', 'can find reactor'), ('controll_reactor', 'can controll reactor'))},
        ),
    ]
