# Generated by Django 2.1.5 on 2019-03-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0064_auto_20190301_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'permissions': (('view_company_stock', 'Просмотр складов компании'), ('add_company_stock', 'Добавлние складов компании'), ('edit_company_stock', 'Изменение складов компании'), ('remove_company_stock', 'Удаление складов компании'))},
        ),
    ]
