# Generated by Django 2.1.5 on 2019-03-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0068_auto_20190304_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autodonor',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoColor'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='engine_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoEngineSize'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='engine_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoEngineType'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='helm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoHelm'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='kuzov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoKuzov'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='privod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoPrivod'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='probeg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='transmission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoTransmission'),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='vin_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='autodonor',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lk.AutoYearProduction'),
        ),
    ]
