# Generated by Django 2.1.5 on 2019-03-07 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0070_auto_20190304_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetal',
            name='detal',
        ),
        migrations.AddField(
            model_name='userdetal',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdetal',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lk.Photo'),
        ),
    ]
